FROM debian:trixie-slim
LABEL maintainer="Chris Isler <christopherisler1@gmail.com>"
ENV TERM=xterm-256color

RUN apt-get update && \
      apt-get install --assume-yes --quiet --no-install-recommends git tmux golang \
      wget curl man ca-certificates sudo build-essential tree locales less gh vim \
      gpg gpg-agent ssh file bash-completion xclip python3-pip python3-setuptools tig

RUN group_name="$(getent group 1000 | cut --delimiter=: --fields=1)" && \
      if [ -z "${group_name}" ]; then \
        groupadd --gid 1000 devuser; \
        group_name=devuser; \
      fi && \
      user_name="$(getent passwd 1000 | cut --delimiter=: --fields=1)" && \
      if [ -n "${user_name}" ]; then \
        [ "${user_name}" = devuser ] || usermod --login devuser \
          --home /home/devuser --move-home "${user_name}"; \
      else \
        useradd --uid 1000 --gid "${group_name}" --shell /bin/bash \
          --create-home devuser; \
      fi && \
      chgrp --recursive 1000 /usr/local && \
      find /usr/local -type d | xargs chmod g+w

# Password-backed sudo is intentionally unconfigured for now.

RUN printf "[user]\nname = Chris I\nemail = isl.chr@proton.me" > ~/.gitconfig

RUN sed -i 's/^# *\(en_US.UTF-8\)/\1/' /etc/locale.gen && \
      locale-gen en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
